name: Build and validate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: |
          sudo apt-get -y install graphviz
          ./gradlew build
      - name: Test code by creating local workspace file
        run: ./gradlew run
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint
          chmod a+x ktlint
      - run: ./ktlint --editorconfig=.editorconfig "src/**/*.kt"
  test-image-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: ts-graphviz/setup-graphviz@v2
      - run: script/generate_images.sh
