#!/bin/sh -e
DATE="$(date '+%Y-%m-%d')"
SHORT_SHA1=$(echo "$GITHUB_SHA" | cut -c1-7)
export BUILD_CONTEXT="$DATE.$GITHUB_RUN_NUMBER.$SHORT_SHA1@$GITHUB_WORKSPACE"
echo "Using BUILD_CONTEXT: ${BUILD_CONTEXT}"
exec "$@"
